version: '3.8'

services:
  todo:
    image: openjdk:8
    restart: always
    volumes:
        - /home/ubuntu/todo/todoList-0.0.1-SNAPSHOT.jar:/root/todoList-0.0.1-SNAPSHOT.jar
    ports:
        - target: 8080
          published: 80
          protocol: tcp
          mode: host
    entrypoint: java -jar /root/todoList-0.0.1-SNAPSHOT.jar
    deploy:
        mode: replicated
        replicas: 1
        placement:
            max_replicas_per_node: 1
            constraints: [node.role == manager]
    logging:
        driver: syslog
        options:
            tag: "todo/{{.ID}}"